apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: jenkins-x-testproject
    provider: github
    repository: 2july
  name: jenkins-x-testproject-2july
spec:
  description: Imported application for jenkins-x-testproject/2july
  httpCloneURL: https://github.com/jenkins-x-testproject/2july.git
  org: jenkins-x-testproject
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: 2july
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/jenkins-x-testproject/2july.git
